---
- name: Página de mantenimiento UP
  hosts: devicef5
  connection: local
  become: false
  gather_facts: false

  vars:
    provider:
      server: '{{ ansible_host }}'
      user: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
      server_port: 443
      validate_certs: false
      no_f5_teem: true

  tasks:
    - name: Obtener pool members
      f5networks.f5_modules.bigip_device_info:
        provider: "{{ provider }}"
        gather_subset:
          - ltm-pools
      register: pool_info

    - name: Mostrar
      debug:
        msg: '{{ pool_info }}'

    # - name: Filtrar miembros del pool
    #   set_fact:
    #     members: "{{ pool_info.ltm_pools | selectattr('name', 'equalto', pool_name) | map(attribute='members') | list | first }}"

    # - name: Deshabilitar pool members
    #   f5networks.f5_modules.bigip_pool_member:
    #     provider: "{{ provider }}"
    #     pool: "{{ pool_name }}"
    #     host: "{{ item.address }}"
    #     port: "{{ item.port }}"
    #     session: "user-disabled"
    #   loop: "{{ members }}"